---
- name: Inlcude zsh variables for specific OS
  include_vars: "{{ lookup('first_found', zsh_os_variable_files) }}"
  tags:
    - zsh
    - zinit

- name: Install zsh
  import_tasks: "install_zsh.yml"
  tags:
    - zsh
    - zinit

- name: Configure templates
  import_tasks: templates.yml
  tags:
    - zsh
    - zsh-templates

- name: Install zinit
  import_tasks: zinit.yml
  tags:
    - zsh
    - zsh-templates
  when: zsh_install_zinit
